// AnimationPlan — Declarative API for scripting element transformations.
//
// A plan is a JSON-serializable tree of steps that describe how elements
// should move, spin, scale, and change over time. Plans can be:
//   - Written by hand
//   - Generated by an LLM from natural language
//   - Composed programmatically
//
// Example:
//   {
//     steps: [
//       { target: "element-1", action: "push", force: { x: 200, y: 0 } },
//       { target: "element-2", action: "push", force: { x: 0, y: -150 } },
//       { action: "wait", durationMs: 1000 },
//       { target: "all", action: "stop" },
//     ]
//   }

// ---------------------------------------------------------------------------
// Element targeting
// ---------------------------------------------------------------------------

/** How to refer to elements in a plan. */
export type Target =
  | string            // element ID
  | string[]          // multiple element IDs
  | 'all';            // every element on the canvas

// ---------------------------------------------------------------------------
// Actions — the things that can happen to elements
// ---------------------------------------------------------------------------

// -- Impulse actions (instantaneous) --

/** Apply a force vector. Adds to velocity: dv = force / mass. */
export interface PushAction {
  action: 'push';
  target: Target;
  force: { x: number; y: number };
}

/** Set velocity directly, replacing any existing velocity. */
export interface SetVelocityAction {
  action: 'setVelocity';
  target: Target;
  velocity: { x: number; y: number };
}

/** Stop all motion on the target. */
export interface StopAction {
  action: 'stop';
  target: Target;
}

/** Apply a rotational impulse. Adds to angular velocity. */
export interface SpinAction {
  action: 'spin';
  target: Target;
  /** Torque in radians/s (positive = clockwise). */
  torque: number;
}

// -- Animated actions (play out over a duration) --

/** Move to an absolute position over a duration. */
export interface MoveToAction {
  action: 'moveTo';
  target: Target;
  position: { x: number; y: number };
  durationMs: number;
  easing?: EasingName;
}

/** Move by a relative offset over a duration. */
export interface MoveByAction {
  action: 'moveBy';
  target: Target;
  offset: { x: number; y: number };
  durationMs: number;
  easing?: EasingName;
}

/** Rotate to an absolute angle over a duration. */
export interface RotateToAction {
  action: 'rotateTo';
  target: Target;
  /** Target angle in degrees. */
  angleDeg: number;
  durationMs: number;
  easing?: EasingName;
}

/** Rotate by a relative amount over a duration. */
export interface RotateByAction {
  action: 'rotateBy';
  target: Target;
  /** Rotation in degrees (positive = clockwise). */
  deltaDeg: number;
  durationMs: number;
  easing?: EasingName;
}

/** Scale to a target factor over a duration. */
export interface ScaleToAction {
  action: 'scaleTo';
  target: Target;
  scale: number;
  durationMs: number;
  easing?: EasingName;
}

// -- Environment actions (persistent forces) --

/** Add a constant force field (gravity, wind, etc.). */
export interface AddFieldAction {
  action: 'addField';
  id: string;
  force: { x: number; y: number };
  /** Which elements are affected. Defaults to 'all'. */
  target?: Target;
}

/** Remove a previously added force field by ID. */
export interface RemoveFieldAction {
  action: 'removeField';
  id: string;
}

// -- Body property actions --

/** Set physics properties on elements. */
export interface SetPhysicsAction {
  action: 'setPhysics';
  target: Target;
  mass?: number;
  friction?: number;
  restitution?: number;
  pinned?: boolean;
}

/** Enable bouncing off canvas boundaries. */
export interface EnableBoundsAction {
  action: 'enableBounds';
  /** Padding inset from canvas edge in pixels. Default 0. */
  padding?: number;
  restitution?: number;
}

export interface DisableBoundsAction {
  action: 'disableBounds';
}

// -- Flow control --

/** Pause execution for a duration before the next step. */
export interface WaitAction {
  action: 'wait';
  durationMs: number;
}

/** Run multiple steps at the same time. */
export interface ParallelAction {
  action: 'parallel';
  steps: Step[];
}

/** Run steps one after another. Each starts when the previous completes. */
export interface SequenceAction {
  action: 'sequence';
  steps: Step[];
}

/** Repeat a set of steps. */
export interface LoopAction {
  action: 'loop';
  /** Number of iterations. Omit or set to Infinity for forever. */
  count?: number;
  steps: Step[];
}

/** Rewind all elements to their original positions and stop physics. */
export interface RewindAction {
  action: 'rewind';
}

// ---------------------------------------------------------------------------
// Step — a single entry in a plan
// ---------------------------------------------------------------------------

export type Step =
  // Impulses
  | PushAction
  | SetVelocityAction
  | StopAction
  | SpinAction
  // Animated
  | MoveToAction
  | MoveByAction
  | RotateToAction
  | RotateByAction
  | ScaleToAction
  // Environment
  | AddFieldAction
  | RemoveFieldAction
  // Body properties
  | SetPhysicsAction
  | EnableBoundsAction
  | DisableBoundsAction
  // Flow
  | WaitAction
  | ParallelAction
  | SequenceAction
  | LoopAction
  | RewindAction;

// ---------------------------------------------------------------------------
// Easing
// ---------------------------------------------------------------------------

export type EasingName =
  | 'linear'
  | 'easeIn'
  | 'easeOut'
  | 'easeInOut'
  | 'spring';

// ---------------------------------------------------------------------------
// AnimationPlan — the top-level container
// ---------------------------------------------------------------------------

export interface AnimationPlan {
  /** Optional name for display/debugging. */
  name?: string;

  /** The steps to execute, in order (unless wrapped in `parallel`). */
  steps: Step[];
}

// ---------------------------------------------------------------------------
// Example plans (as documentation)
// ---------------------------------------------------------------------------

/** Push one element right. */
export const EXAMPLE_PUSH: AnimationPlan = {
  name: 'Push right',
  steps: [
    { action: 'push', target: 'all', force: { x: 200, y: 0 } },
  ],
};

/** Two elements diverge, wait, then rewind. */
export const EXAMPLE_DIVERGE: AnimationPlan = {
  name: 'Diverge and rewind',
  steps: [
    {
      action: 'parallel',
      steps: [
        { action: 'push', target: 'element-1', force: { x: 100, y: 0 } },
        { action: 'push', target: 'element-2', force: { x: -100, y: 0 } },
      ],
    },
    { action: 'wait', durationMs: 2000 },
    { action: 'rewind' },
  ],
};

/** Gravity with bouncing. */
export const EXAMPLE_GRAVITY: AnimationPlan = {
  name: 'Gravity bounce',
  steps: [
    { action: 'enableBounds', restitution: 0.7 },
    { action: 'addField', id: 'gravity', force: { x: 0, y: 400 } },
    { action: 'setPhysics', target: 'all', friction: 0.02 },
  ],
};

/** Choreographed movement. */
export const EXAMPLE_CHOREOGRAPHY: AnimationPlan = {
  name: 'Square dance',
  steps: [
    { action: 'sequence', steps: [
      { action: 'moveBy', target: 'element-1', offset: { x: 200, y: 0 }, durationMs: 500 },
      { action: 'moveBy', target: 'element-1', offset: { x: 0, y: 200 }, durationMs: 500 },
      { action: 'moveBy', target: 'element-1', offset: { x: -200, y: 0 }, durationMs: 500 },
      { action: 'moveBy', target: 'element-1', offset: { x: 0, y: -200 }, durationMs: 500 },
    ]},
  ],
};

/** Spinning with friction slowdown. */
export const EXAMPLE_SPIN: AnimationPlan = {
  name: 'Spin and slow',
  steps: [
    { action: 'setPhysics', target: 'all', friction: 0.3 },
    { action: 'spin', target: 'all', torque: 6.28 },
  ],
};

/** Orbit-like motion using perpendicular forces in a loop. */
export const EXAMPLE_ORBIT: AnimationPlan = {
  name: 'Circular orbit',
  steps: [
    { action: 'setVelocity', target: 'element-1', velocity: { x: 150, y: 0 } },
    { action: 'addField', id: 'centripetal', force: { x: 0, y: 150 }, target: 'element-1' },
  ],
};
